# manifests/infrastructure/external-dns/cloudflare-token.yaml
apiVersion: v1
data:
    CF_API_TOKEN: ENC[AES256_GCM,data:7j+yTOgDKGwXW+7JMzj6wnxSSahSi3l5xKs3scExKGQxoQ3b+gMucMwYeliBPxRqh3CA1SlFfho=,iv:rqey7nt+RhITAf3Z3nk7HXXYk81KXct2/Hjw5vBE2yw=,tag:3q1uEPPMVPHDTrOn7vZeBw==,type:str]
kind: Secret
metadata:
    name: cloudflare-token
    namespace: external-dns
type: Opaque
sops:
    age:
        - recipient: age1f4678pd55d3a4usf5qln6yslq7lawvy0ykzkqm6hm2j96eu2p34q8x9wg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNHFYQUh4Vk85bitYaFVD
            ZGZLWUxmdTV5MnZSZlVKdXp5THpTWkd5aVI4Cnd3MXAva3lxRTgzKzRiWTdQY0Mx
            MG5rcnZYeXFEMkhmMmtkYTZTZTdpbncKLS0tIGM0b2dQZDBrTENPYThNMFllSm5n
            dzludi9WakM5TnpEZFk4YmVCU2pFWjAKStnuopyL6KpeDwe7G3Bk3CridD+JQKL8
            JramqS6sTVAGwFheT1v2KcFoKNAjjhBTIzTIsDGOqr4EqnzFHSJlSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dxvrdmtyp37gmmcqg28uftsujp6scj0p6zelgu3ctr3sky52usq7767jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSzNGcEp6N3JuQ0JQWmxl
            cVo1SlVWNjAyS29yMXlubEFJM1hNWExSNFVJCkViQlVWbEZza25yU2FJeUV0bEs0
            WlZTVXV6elRiUDJheWhiSm5GVDJoNWMKLS0tIEZhanBrM1hJQ1NISTh0MUQxSi9o
            ZG5RUXRjL1pyS2lOVTliczluNkYwZjQKIotn9VW1iH/EEpUISQsal1qNbXfJAjCV
            fbOc76/FAhkyM6Ia/QdoUlLGp5oCSYapnzMWHKRbs1IsaFnREtWUJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T10:05:48Z"
    mac: ENC[AES256_GCM,data:DuBiFuQH4z6WVSR1jGMsLrVldqyrVG39RNvFqMdBE2oEsjhJCmMM+LGZrR7QcNfsS8Xj3Bl2Q8MsNDqgUGds7EZU95rVg1uEEa7nXOEel0ODrwBOVYIlH1HklZDDXoSOEhlEb1uImWUkiWrSe72Jc4bCY13tFLl0H4yFni7oUi0=,iv:62f7tvI4KTEMAoyPpTbdYjxt1agQdcMrjwgxshKpxto=,tag:TIwCw36k8w9lhajxNuE6uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
