# manifests/infrastructure/hcloud-controller-manager/release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hcloud-controller-manager
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      version: 1.29.0
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: kube-system
      interval: 1m
  values:
    networking:
      enabled: true
      clusterCIDR: 10.0.0.0/24
