# manifests/infrastructure/hcloud-controller-manager/secrets.yaml
apiVersion: v1
data:
  network: ENC[AES256_GCM,data:DlJiWnfGAWu0lInW,iv:HH9etpdhnNYMO5n1jEJXxsHO+RTgcba6pqKavMqMhXg=,tag:c0vDYP7SQSoSsR4+dXfPQg==,type:str]
  token: ENC[AES256_GCM,data:CvT7icgOTs4h98M+uaCLFvC8QnNNhcbLRe40IeaWq3qgsDE/uu/CdkqsdPDQxchVzf9xUdvAN7yZyFjw9TSkTvyKF7Sx2EjY3L00PJvwog92j/q6tER/MQ==,iv:rIAgdkiZligOcogE5OdMpb1ITkoNnv6/rMQ+b4ghkUA=,tag:nZK9Dx0sfLoYaKLYUJfFaQ==,type:str]
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
sops:
  lastmodified: "2025-11-28T23:10:17Z"
  mac: ENC[AES256_GCM,data:4AKmf985EFx2P0926vGn8jn8b6uA/1G8u3sM7nemXov+vms7+BmJKv9S709TttFtpuEvlkb/ZQLzZOjOKULkYeYqhPNcC5SM0O4D5MNLSdBtKm8pHwpXyppXlYU/Mljmarw3w8Eb+oOsO7+5AlQJAWD8hw1CD+cgNM9R5Wka6cg=,iv:Z26U6yUpmFUEdFOU1spTVaj+RbmcAp+lGVdwU++WyYo=,tag:CTHJbigs5EKHPfBSB38jcw==,type:str]
  pgp:
    - created_at: "2025-11-28T23:10:17Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DD39ke7DWyjoSAQdAsz709S6cYUwSXRMqbV4kvcrbp/TeXT2I9Gu0CTCkYBQw
        aJJJce7r3UATypkRYsedfTvIuBWJC3iOzQg4KBcDf2vHxwXa98kmL/4tIVoJ1bAo
        1GgBCQIQlsWuubyuMOgwo+wiP/xyaCIZfVB+l+jrgSsrXta+Sk0Yk9nE8UKNGmU7
        KFDIjMVoaAEJZWde9mfbgXYOgzjeZW6IWfruKRMQNE5b1va/hoKomr+wDMZ94p3c
        re9Rv2CEHn/1FA==
        =pSrd
        -----END PGP MESSAGE-----
      fp: 36CE22BE4013AB02D13D37429CA6D02C1BFE3F11
    - created_at: "2025-11-28T23:10:17Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2mLLTvi2YCoAQ//StGmGKpVTxkyjXd5FQ5iubrjU4uq4LPMXy8OMDWswJwy
        U+VcBTr1mwJep7xceBN5/5WuD7LG5FV5ywzvqpwhXkhNwGrz2TZS7KHC0jzHcSNk
        4i1QGDzq+hjIZSeP180+kDZgYkg9s4byAhAeaVx4YUYdis7QMbAzjxPTXCBb2s/b
        OwT5oGSiUA8joktICQo5a6S66EHoQGahTNFov8U6ZO/6EQpOqRSwypJWnvqZDJze
        Fpq5nUq9o687ekigDCZiCT7qhD8nT0JgiUTVjXaUJNifhnELW+n3FtKSJYQaIGp4
        k9nL6LlrfFfwKglw3FZcZC95LEOqD8V4QE3wAXwMPm+RmkWX42dSBzuWvx35BtTt
        SGRSPmMJ04ElGTtO8nkCwOxjz+JwvcroSFErHd7zPrOXezEcaDrn/pglVBBLGTG+
        D0CLOevpE0gaA+jq2E/vZF9aGcOp1KyfjvHad1eVbeG9j4XgcOApSjcm3jEDxmZ3
        WASDQxZ/wYQAhqwZUiK0ZQYvdQ/bwKEmPZU9meREFGO0DKtx6YoOQq51rcXSUvqs
        OubGvnrrhGlt9C2OwkKBh08H//R1Uxe4dldTBHnHa1n8shAY+HqTiT4u4/jPpe8F
        YMS2x9xFQmvf1xrc6RNJXX0/dteWm1kL0EQcB1Amodara0ai6pnT8vLka3GipsbU
        aAEJAhCWR8S94mIU/GV9G4KOduZq0i5vnY/XIUoXx5cddMvCVbsBlVKEblO6iCNF
        p1k0yGiXydWKnX71Pk4ppKAx3A1oVH72rDdb9aZAOrulHVdRKy7seCjaBkubluVv
        qxCc9rDNGav9
        =dG3S
        -----END PGP MESSAGE-----
      fp: 0FC1070248E009EF18EF8F3A3C17E467E8763D54
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
