# manifests/infrastructure/hcloud-controller-manager/secrets.yaml
apiVersion: v1
data:
    network: ENC[AES256_GCM,data:Pr3LkYlSJZnI4vxM,iv:/zIB82EI7RwbHkFARuEZvsZsjOoFe8WKQjoMglPulp8=,tag:Q0VmUy0Ov4MYQXM40FNe1A==,type:str]
    token: ENC[AES256_GCM,data:HRcgSBTK7nPMlWFClLfLiN2q6Q2YmcnlPlx3ulBUNvETLo7tInzxKNR/RknsCUVmsbtps64qbfk3r+HzUl5GjRo8H3voFb6pCttRgTqLnlctj2wMSLes2A==,iv:oZfJfdP73PneALeqOLvLbd8e2KjhEMVsrZIiaufsqpo=,tag:cfq+NbGB8GS1E+CmjvguyA==,type:str]
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
sops:
    age:
        - recipient: age1f4678pd55d3a4usf5qln6yslq7lawvy0ykzkqm6hm2j96eu2p34q8x9wg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQjc5S2gwNzFrZjF2VEwr
            TVVFT0JiejNsdGhUNXpBdy9rMVpuUnZMZ0VBCmFaL29iVE5nRFgvTzZlUUEwa2Rz
            M1dMMzNUMmZ0WVJJOHBoMXMyeEZTb00KLS0tIFJpREJVTG5RY05tSFpTbUNjN1pH
            SzV3Vm1DZmtIbkFvSlNLQlhtWW5TWTQKF1DFPLicTTGHhQYJa7SVQb608V6RAZTk
            EvTIAG0yqMrqHTqBE7m2BHlhJJJGRmdWn30OYLnCpG13aH9fE0+pSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dxvrdmtyp37gmmcqg28uftsujp6scj0p6zelgu3ctr3sky52usq7767jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd0t6QS9SVnNGdVdVOC9P
            dXg0N0t1b2kvQlhRVW5WSVU3bkRoaWVPaldzCnNQWlFsbkR1YU5tb3ZvbjRWY2dI
            UHhwZmt5QUZ0VDN0dGxCWTh5Z3NZR3MKLS0tIGFlaERnRmZWMnpHdzJmQTdjRTJ4
            U0JJK0lsODlUZEFtdEZVTTJYMGhlMVUKei8WooXEuaI04OGvrvyBVnDRifQJlyrm
            ZcZSYm8IXzUUwmqbAg2l0dHrqaIynTTC6o96pQAaYjSu8kmkIwBo3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T10:07:08Z"
    mac: ENC[AES256_GCM,data:KF2/x4u/AxLkYjJxvg0G26E/ntMCy8tUpF21DmfOqq6BxdXlhOdYkJzNIJora4P/0F1IXHCLAVNNkZQGWZGGM6/UYajqlfTXVypCq/mOkezsX6Oad/tovObppp0mdb2CiIg+FpIT518GDofM2g8Cl6OAGivbFHU7Gtaw2XNApvw=,iv:OFZ6WwZ4k7nFQvpPUqhtNpPRE2pFOQxGRsIxnTfy3ac=,tag:4yvGOGDFHSIxf7H7OtC6sQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
