# manifests/infrastructure/rustfs/release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustfs
  namespace: rustfs
spec:
  interval: 5m
  chart:
    spec:
      chart: rustfs
      version: "0.0.78"
      sourceRef:
        kind: HelmRepository
        name: rustfs
        namespace: rustfs
      interval: 1m
  values:
    replicaCount: 1
    mode:
      standalone:
        enabled: true
      distributed:
        enabled: false
    storageclass:
      name: local-path
      dataStorageSize: 3Gi
      logStorageSize: 512Mi
    secret:
      existingSecret: rustfs-credentials
