# manifests/infrastructure/rustfs/repository.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rustfs
  namespace: rustfs
spec:
  interval: 5m0s
  url: https://charts.rustfs.com
