# manifests/infrastructure/rustfs/secrets.yaml
apiVersion: v1
data:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:sXs2NB7t1op7WqDcwydQ9g==,iv:gMGA+lGQE+fTJ7lhzI4o0LmwPUyli8YploS31kf41Oc=,tag:OQPRzL8XkvH9EkWRB1w7xg==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:bJ7pjFhLQDsVyCJewAnbXMQph/79LqLFgvo0Z1bOq+Ah994foUG6ksw5sXs=,iv:SoYZcyLNqxB5CJX/XptOm7j+l1gLdyhcy3OpEoltMYg=,tag:K2X+kNoPAddWmmUgDa6KvA==,type:str]
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: rustfs
sops:
    age:
        - recipient: age1f4678pd55d3a4usf5qln6yslq7lawvy0ykzkqm6hm2j96eu2p34q8x9wg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVjdjZHFiUjNOWWw5OGd5
            WHRmNGFTUFdFTG5GZU02SmZGcDJ0QllJWkNJCkpYSVlEZFFEeUhxSVptZTJpM1I4
            N1RGK0NRU1FqaXhKYURoZVZSVnkzdGsKLS0tIFZKdVYySkxzeXQ3Rkx1N3pIdE1D
            aHdHSEZaZG5pTk1veUdQRTRuTFlwZ2MKtC/FEXgYxB6Vh0+vwo6oLSOkjKk3fqNM
            szZ3unL79ac125EwSY5E+3UrE9y71CvV/tpaSwqZ4+uBuJIDp8LZvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dxvrdmtyp37gmmcqg28uftsujp6scj0p6zelgu3ctr3sky52usq7767jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdFhaQUd5YUJqT05ISVd5
            cjhqZFkxREt4ZGRzNWI4SWRnV2hwTnpuNEJNCmVJYjJobGZrakQrTm9jWlFXUkpD
            MDRZZ1ZXVXFMUXZVNFA5cUlCWXVZdFUKLS0tIDd0ekJpK3JseVhXaUNyOXhZRWtl
            T01VSktuSzBxNXZmcEFJYkdCT29SN2sK4W/MW9C1PBcHrUOyalEcVBhsxYbSesS6
            CE0Yt87LP9bU9R0cItUPNU/DcZyFmA51Sr59mkcMre7HZozT+XbpSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T10:00:20Z"
    mac: ENC[AES256_GCM,data:Cqg7kUxjViarfgXxfoPKNrouXrp0BX+h7cHCAUSDq1VAoAZhBVvh52uatNo08fmXXgRC4EyxV+GaQwd4V8D2KexztW4MtwW//kWZLNq4W7xfulcIlMnxEJjQ+kagLKxGrYHgF/aRGiJhF8UlGsatSLAwyZu/gmIvGdEWD2y/jJk=,iv:HlXjtkymkg4l/LvJCQHL9j1+8oDX3aenKru1HY8FsCc=,tag:XYQTXN/ng3IhSS6XOEqw7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
