apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - cilium.yaml
  - pull-secrets.yaml
  - traefik.yaml
  - podinfo.yaml
  - external-dns.yaml
  - cert-manager.yaml
  - hcloud-controller-manager.yaml
  - renovate.yaml
  - local-path-provisioner.yaml
  # - openobserve.yaml
