# manifests/infrastructure/openobserve/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.87.0/bundle.yaml
  - namespace.yaml
  - secrets.yaml
  - repository.yaml
  - openobserve.yaml
  - opentelemetry.yaml
  - collector.yaml
  - httproute.yaml
