# manifests/infrastructure/openobserve/release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openobserve
  namespace: openobserve
spec:
  interval: 5m
  chart:
    spec:
      chart: openobserve-standalone
      version: "0.20.1"
      sourceRef:
        kind: HelmRepository
        name: openobserve
        namespace: openobserve
      interval: 1m
  values:
    config:
      ZO_TELEMETRY: "false"
      ZO_TELEMETRY_URL: http://127.0.0.1
      ZO_WEB_URL: https://obs.talos.detainedu.com
      ZO_LOCAL_MODE_STORAGE: s3
      ZO_S3_SERVER_URL: http://10.244.0.26:9000
      ZO_S3_BUCKET_NAME: obs-talos-detainedu-com
    persistence:
      enabled: false
      # size: 5Gi
    # ingress:
    #   enabled: true
    #   className: "traefik"
    #   annotations:
    #     cert-manager.io/issuer: null
    #     cert-manager.io/cluster-issuer: cloud
    #   hosts:
    #     - host: obs.talos.detainedu.com
    #       paths:
    #         - path: /
    #           pathType: ImplementationSpecific
    #   tls:
    #     - secretName: obs.talos.detainedu.com-tls
    #       hosts:
    #         - obs.talos.detainedu.com
    extraEnv:
      - name: ZO_ROOT_USER_EMAIL
        valueFrom:
          secretKeyRef:
            name: openobserve-credentials
            key: ZO_ROOT_USER_EMAIL
      - name: ZO_ROOT_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: openobserve-credentials
            key: ZO_ROOT_USER_PASSWORD
      - name: ZO_S3_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: s3-credentials
            key: ZO_S3_ACCESS_KEY
      - name: ZO_S3_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: s3-credentials
            key: ZO_S3_SECRET_KEY
