# manifests/infrastructure/openobserve/secrets.yaml
apiVersion: v1
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:Ury+0dwMgr1Ij3p2bLk+MWw78NnDNPYY,iv:ikDdlNQpJn5nF5uOoSzcZ0cEAfvg3JezOuitZc8G3VM=,tag:csnf3i9GCRjnT5nJxVIGmQ==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:pnn4R1tikvZCmvkOSZrGq6XSkgimAgfT,iv:zgSz30AYRnhND+Hpyejax8Obh/jyPYrtXapNqnmFu+c=,tag:tqS92H18SB19VaZZz1Nzgg==,type:str]
kind: Secret
metadata:
    name: openobserve-credentials
    namespace: openobserve
sops:
    age:
        - recipient: age1f4678pd55d3a4usf5qln6yslq7lawvy0ykzkqm6hm2j96eu2p34q8x9wg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY2VqODVGN1AydkNTQnNr
            c1dydkRXMjcwNXlMQzZTdTRORUtCWWRhQTNBCkE5RHlMdkI4V3BTNWxkLzE2eWRp
            NnN5UmJ2YjBYL0p6eGIrNVo5VDVoTE0KLS0tIEt5cjlMRDcyRlU0WEdWOWU5U3Ns
            RTlXRWpaUGZtWk5za0dDdlU4Wk5kQXMKtLLOaNxVMSHbIuJ8U18HlHKyZi2j99VR
            oDOv2m/draqbTrZpuzeoKbZXu5ApvMCs25jbSzEr3yzUxzo54Hvxjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dxvrdmtyp37gmmcqg28uftsujp6scj0p6zelgu3ctr3sky52usq7767jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTXB0UU9ydllmRzU5NkJt
            bGdXRUZWZHFxZHFoNWZScjlib1ZXQTJEU2o0CmltZDlZU0VKYjBFSElhS0swWmNx
            YkxiTGFybFZDRjcwR3BIQWcrUWFXMWsKLS0tIHhsV0YrWm1jTHltK1o1YXI4UmRw
            SWc0S1BLQjNvYWwvTDN2YzlSVXR1SnMK4Y8OkAg3o9L5BYYONO0Mv98IjHzKy2WV
            odWGPi882Qr+ORzOZsfZ2yqBiFYlpTnSF6bI0HcphfDkMUI4C1hw2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T15:39:27Z"
    mac: ENC[AES256_GCM,data:KVB80s4hRijS3HZnBCNwqw8+FnnkjicPXyY9GJ+mpMlMTnhXp03v0D/2iuhCcAlGbOqkieNILObr3UdgMMVKaE2SEZX1v1r2KpHbAQsIw9ghTpFb6cLT3sQzUf7yKcEPpUoZCR8WxEXeaIn4K7sQIGEhoNqzID8tpmE4+jrE4Og=,iv:i+wzbrhSxQOWCBSirDl/VGDHXeTFAxj99I7dr3iNDyc=,tag:yc85lY9clBtIa1TBHHNC+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
