# manifests/infrastructure/openobserve/secrets.yaml
apiVersion: v1
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:Wdagkb4+W+a5Cb8Mpab4LeHoW6yD+yab,iv:rFyzlrJdyD0NwyDFWbXOE8nM+jgUsLDyhPtfzNDgOTA=,tag:wNCDqzWSfFZA1e7ed8YfYg==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:5ri9Njo7JeRKgZy0d+rfm8GZ9Vqb4xgq,iv:fZA/2al/oxDQneA/bX5hWTunWYOTR7N/6nEIb3J1L+I=,tag:j9rR/UP3DRv3NghH5RHrYA==,type:str]
kind: Secret
metadata:
    name: openobserve-credentials
    namespace: openobserve
sops:
    age:
        - recipient: age1f4678pd55d3a4usf5qln6yslq7lawvy0ykzkqm6hm2j96eu2p34q8x9wg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd0tYNm9MUjR4ZHFTVzlX
            UkhURkNBbGxDUXc5WWJuUXV4YTgxZUFDVlVRClA5cEYwaTh6UU5FZUd0WDk3OEhz
            LzlUbERUZnhBUkFaRElKbWx3U1NXMncKLS0tIFZMUnFYMUR4elYzK3JxREVXRi8r
            U2tDT3VXMG5TR3ZtaE50RVMyN0sxRk0KSPThzMRRV//Gf5s0F8TwxHaSO9f6oQHR
            kwIje+IlYjJNHLMj6KtB5BniKQYEr7WKEGiT2uYPf1qn3iMysEPG9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dxvrdmtyp37gmmcqg28uftsujp6scj0p6zelgu3ctr3sky52usq7767jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeTFZM0ZSOWxqa0NqR01C
            V05CbWlGZ3JKNHBVUWo3OGc5Y29HbEhtcDA0CldqL0ZkMktDTjJGRGZwSWtsT1NO
            blgxZ1UwQ09oWDE3ZkNUeEl5Wk5ZV1EKLS0tIFEwYXRtdnE0MkVhRGRBNThNT0c5
            U1RDQU9FTWR4YWRkNnlzZmNWUkVLTDQKLaNAFWsCIXrIfL1XAUPYTdRW33VJ1qrQ
            c+Mb0ex4dpM5nXn3V9Pu7ImpZ9ENQFe7+xa+Y/Y2UhfnmYOgXxRM4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T00:13:25Z"
    mac: ENC[AES256_GCM,data:Lxb9GIuvSo5jdxgbyk7R/ebygVBLDvPL+9pfYgIpUqEvvH3KrVUHL6BKMJvgzQpA7Sr3T39N5K+viYtQl2c6mVGovBitfV5tO1oQqhRUOkNdmB3X1ZWkfyLEAFm+OUieSo11zzF6NYlXEzMvs3Q8HCYLvlEQyHWsrBtNfI0BNtM=,iv:mjUehs9Sm+TrtYFp/y97l0THVAQR6J4OGXSRRWyD3hQ=,tag:nPjr9klNYa6YQDoEfMtquA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    ZO_S3_ACCESS_KEY: ENC[AES256_GCM,data:ZFqlKVUF7HqPrL6AX87qo826OhE=,iv:EztXRICtXNrwiENMSD8Ue9azTeW17NqFLnxIo5dQDD0=,tag:LifTCLXi1iuKMkgI6b/v5Q==,type:str]
    ZO_S3_SECRET_KEY: ENC[AES256_GCM,data:0J42xJrcIcfQA0a4LcBta+cz3y2U3CxSIQmVl8qwdyO2nEzB4tjEGQ==,iv:XwEhNDY79oDk+3/7tan5IAD5K8WYWlikWNgxaEhmoDU=,tag:bCzhpxrj3PqEe0xdKnFhag==,type:str]
kind: Secret
metadata:
    name: s3-credentials
    namespace: openobserve
sops:
    age:
        - recipient: age1f4678pd55d3a4usf5qln6yslq7lawvy0ykzkqm6hm2j96eu2p34q8x9wg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd0tYNm9MUjR4ZHFTVzlX
            UkhURkNBbGxDUXc5WWJuUXV4YTgxZUFDVlVRClA5cEYwaTh6UU5FZUd0WDk3OEhz
            LzlUbERUZnhBUkFaRElKbWx3U1NXMncKLS0tIFZMUnFYMUR4elYzK3JxREVXRi8r
            U2tDT3VXMG5TR3ZtaE50RVMyN0sxRk0KSPThzMRRV//Gf5s0F8TwxHaSO9f6oQHR
            kwIje+IlYjJNHLMj6KtB5BniKQYEr7WKEGiT2uYPf1qn3iMysEPG9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dxvrdmtyp37gmmcqg28uftsujp6scj0p6zelgu3ctr3sky52usq7767jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeTFZM0ZSOWxqa0NqR01C
            V05CbWlGZ3JKNHBVUWo3OGc5Y29HbEhtcDA0CldqL0ZkMktDTjJGRGZwSWtsT1NO
            blgxZ1UwQ09oWDE3ZkNUeEl5Wk5ZV1EKLS0tIFEwYXRtdnE0MkVhRGRBNThNT0c5
            U1RDQU9FTWR4YWRkNnlzZmNWUkVLTDQKLaNAFWsCIXrIfL1XAUPYTdRW33VJ1qrQ
            c+Mb0ex4dpM5nXn3V9Pu7ImpZ9ENQFe7+xa+Y/Y2UhfnmYOgXxRM4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T00:13:25Z"
    mac: ENC[AES256_GCM,data:Lxb9GIuvSo5jdxgbyk7R/ebygVBLDvPL+9pfYgIpUqEvvH3KrVUHL6BKMJvgzQpA7Sr3T39N5K+viYtQl2c6mVGovBitfV5tO1oQqhRUOkNdmB3X1ZWkfyLEAFm+OUieSo11zzF6NYlXEzMvs3Q8HCYLvlEQyHWsrBtNfI0BNtM=,iv:mjUehs9Sm+TrtYFp/y97l0THVAQR6J4OGXSRRWyD3hQ=,tag:nPjr9klNYa6YQDoEfMtquA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
