# manifests/infrastructure/cert-manager/certificate.yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-talos-detainedu-com
  namespace: traefik
spec:
  secretName: wildcard-talos-detainedu-com-tls
  dnsNames:
    - "talos.detainedu.com"
    - "*.talos.detainedu.com"
  issuerRef:
    name: cloudflare
    kind: Issuer
