# manifests/infrastructure/traefik/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - release.yaml
  - namespace.yaml
  - gateways.yaml
  - cloudflare-token.yaml
  - issuer.yaml
  - certificate.yaml
