# manifests/infrastructure/renovate/secrets.yaml
apiVersion: v1
metadata:
    name: renovate-env
    namespace: renovate
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data://0ko1+6n/m6kOOXEuvlpOCr/dxHaSNiy6OMU4LrdZP1PDqL7ZhjDVqRBnVYV0m/XcWhHtTL/8P/AP3hZi07d/9Q3oJq+9UVHbBwl4/tZYW2T0aRCZxP9MGz8j0w,iv:PDqZtgFMAB91tAR/3t+MSazW9JI3a1Oob7vx3udnPhA=,tag:ABwqXeUqzYN5dsFePtMDtw==,type:str]
kind: Secret
sops:
    age:
        - recipient: age1f4678pd55d3a4usf5qln6yslq7lawvy0ykzkqm6hm2j96eu2p34q8x9wg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOUJQSUlFNDV2Sk5zc0RY
            Q1Z2UWVYbmtmV1d3cEY0b1cxdzhFMkx2TVJBCkUvN2gvSDA1TURtSmxqSW9CYUQ2
            R3MrZlhvTlZaTS84MlNCMmtFQXhvOVEKLS0tIFRVbVFiYUs2V2ZBQlRPQXRDN3ln
            TkFvaEQzVGtVRWw3TmZvcVV0VjQvRncK9/jcmcj9nQKbdxII1MqaIXPhs5MGbY8Y
            Bm9Vz/XTbteQL3vAkUR+VdS2NFb/VG6ya8vViiGiioitPjhp9EQs7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dxvrdmtyp37gmmcqg28uftsujp6scj0p6zelgu3ctr3sky52usq7767jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUHBQSXpHWndKRTArbUY3
            NkJDMXFSamlBMUhCUHV4OWNzbHJLVkREL0c4ClR5TEsrZlZ4VzB0QUpqU3d1czBO
            ZEE2TDlOMFY5dURqK05WeGM2aXRlTEkKLS0tIEtZdTdnM2wxTkpTcGJFOGxMamRP
            ajN3SmhXUjc0cE4rZURjcTVMWkhMcGsKJMMi8CsuKfdSN2kgeiklYpvlao7UlA+Z
            OmdsGv+0gJdw+UuXSBZ0P+fMKPTWqucFDalrF3AR6JMxK0IdtaDA+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T15:44:32Z"
    mac: ENC[AES256_GCM,data:xZGgYE5iPK5LTvc0T9fZ68fM05EBn+RKe6MwmG9tww2EUz2wsDcDtkdhDdMif6rqa0gyNAnlTUoumrtHOCLZOALWmvQynVCCecPCPmPwFYRHxn1JCM28XjSLm9n8gyJODXQFs4Hv7Z810HHCswfM7YBkuI9mEMOYcT3nT1XudtM=,iv:dtNoXNrIUCBJP7G88Y4m5m79ePgFCXhUVdOuJSXJTPo=,tag:qy/PTcpBXoIxSMafBKDiLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
