# manifests/infrastructure/cert-manager/cloudflare-token.yaml
apiVersion: v1
data:
    CF_API_TOKEN: ENC[AES256_GCM,data:xVoh1o8YuTY98a+fslvHS5mfJgwRdWijPjxTAszaoMpBrTm0APEKtS4h3/R4CqPk6F+4hRSZFKM=,iv:3WmC7CTTjMUmWRNI5rVHkY/7EL2WH64EmQSWdpRXRQo=,tag:DqXfT8lqMzZnt7WrxWcSjQ==,type:str]
kind: Secret
metadata:
    name: cloudflare-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age1f4678pd55d3a4usf5qln6yslq7lawvy0ykzkqm6hm2j96eu2p34q8x9wg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJS0ZVcTZnUWVYekNoVGli
            T2ZnbEUxa0UvT3FFYVl6UUFzbVNSRkZCclN3CmJ4MTZ0MmhSSzBjREdvLzRyemNX
            RGRaUnpxNExiNFNFa2ZEdjgwVEtHYjAKLS0tIEtOeU0rNG9STDFUSHVXSVRnK0Q1
            cFZ2Ui9heU5PZkJtNHc3TWVwSkl0d3MKek5Ftj60mgkvTQSxQJI1KmMyq1YVaL/M
            5KH8KiKd0h1eq1A3O3LWfhiibUo9Tfk0C/Kb2H30kGK8ZC/BNlVqhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dxvrdmtyp37gmmcqg28uftsujp6scj0p6zelgu3ctr3sky52usq7767jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZDcrbHJDY0tVNWR0dXl6
            aEowbGtZa0RIcU5iUmlHRmpkMXRSc0hQWHlJCmVqVFRENnc1czhJSU5ZZmFvLzho
            SEhnc0ZXaEVhdjloZnc4NU1Fay91bGcKLS0tIEJhclhUUXFjL29YaHJuMVpaTFhH
            bjJhU2NtcEs3WDFYNHpHVC9hdGZzSEEK2TmksYa1y1fUiVj2qRtFiht4tfi61MqC
            v7h22GaT0JYyN2Lt1XqODs+v6vt3RZbPb8xQ4jbILEO8W4tDok1jIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T10:03:00Z"
    mac: ENC[AES256_GCM,data:RLFA1y5gyQy2hHmphdXw5udxyhpEXdeB7/8IijwzUK1ok3BgOd7x1J4eI+9P/f//rQCNgH0PXp28+xcBpKoafe/XWiVLYWKbqAgKlHJCHlbCEfDpo/vKzNE03nSJYHlJkrfEDxi/cPEqv9tcAnwWzsNSL+7/ShtwMfJB4R16Y2U=,iv:QvHl6GR27mdPGuxpoXXi/q+Rcxoq2u6zVCF6aK6JUEE=,tag:qV4LWUxDVV0F6JI4nIv2Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
