apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:3y7h2dNGVe8zDR3LthbewOF9ajJRIEMCFrao6+7CcTlY1eznPINwwIteWlvY0tbBAvFw+6dQ+mGCNNqgPFs5xse9ygYHzYtzvaucCzNtRHvygJw8xd2EkTfpgnas8czx0h4e7L+v1GY3zIAGwm5CSp6CvifqFH8ITzQtnmg3fWHU8CnrgLcmw93K17r7Bk3UU8cb2aewAJbSUU3echWJUG3t8WOq21XZv2hcLu+ZQzQtRhr7/i/5GJ8wC2OWxZyi6iSdotJaVStGH73kmODH8Kx7WPYSzqKXecUTinkzgylSm4QAKa7uyxUWfg8NkpluuA+I+dcJFj0=,iv:S3Z5K2+ZypP5QCMEPRoigscQOR7n3vYBPsRUxpVHpK8=,tag:HTeWhz/6x6Nrk+nqGVl+uA==,type:str]
kind: Secret
metadata:
    name: my-super-docker-hub-pull-secret
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1f4678pd55d3a4usf5qln6yslq7lawvy0ykzkqm6hm2j96eu2p34q8x9wg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVUZPanZEak5ibjJMVmo2
            K1ZLQmVuc2Rybmc4V2c5ZlpWWjVvS3ZCYkdnClhSa1RJc2lTWUpOK1ZybFc1ZEVx
            UHA3SUQreEp6aDVXWnVsOVFLOFh3LzAKLS0tIGt6RzRjY0l0bHUybWxlZGZYaVJh
            L3FMemI5YktaWnBxZndiM2R1VVB0a2MKECf5dSdzR46IM41yNzOA+tMK5RIlAe5l
            nS9of9wXjeL40QD1HeH58MtYaSo7OeR4Sz610RQjuUZWiEn6VBtn+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14dxvrdmtyp37gmmcqg28uftsujp6scj0p6zelgu3ctr3sky52usq7767jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMWtGdnBaSEcvbFU4Vnpr
            dGtkclllQW0xSFArT3FhL0tNZmFCTUNxeGs4ClU2UWZKeXpiZTFSVW80SmRhZzg3
            NEdHTm8xL2haWGU3b0MrQW5ETGlQbUUKLS0tIE9acTd5TDB1SENPSFdRNStBUXBI
            VGFQNGVHRjRyTU10dktXby9SbTB4WVUKhb9gDu2yKKkzY/a+Eai5mlblawr+06L/
            RhyoFsVWqjpNaQr4y0TLhB6Y/leu1Ukb2C8l9DcFiSMp4FQdxR5X+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T10:06:28Z"
    mac: ENC[AES256_GCM,data:QrLg1aQV8ou9zzT8B9So+romXaV1AZRdu6/UJQnmyF6BBoGnG8wZQ9i4zA/2e3V2o0fXTritTcmEtqTA0JzKo9taNUIaxvdF1pjlWu2B82x6tuTEfrArHiuPC5FjbWPV7okBOxa+xSdRmO/0HdvRnvDAVy+sxpmwaBWUgDoI5JM=,iv:4NyRaK1i3QgLgiHJIfcZ55C8qp0QPBrAaeDEbv2E/oo=,tag:B8uj3G2mDEsFG/00Oe5caA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
