apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:8OALKNwPDh6kFmNJE8o4+GOv0RJZHY2R4SwPV5P96vOwtib7C6Y5n6ph1P/95E2UI6X4Rat7ROH6Hz9SwR/kwDjL63srTBjirCV6uSvqoJQ6hkxkSUMLswt0SVRrGJQySp+BEegkSpDanm/sx0RyJWH8rRKlyO8nnFa8FFkAQs2Rf7Zl0+fvTkwU48+CdCssiWiy9zSjS9AjjvQJ8MQ4RUj3Is/LZ3BpPxCq23aTBf/l0aLQ8X0rlG9Vm+ZvZaq7xxgLM4LG0ZPX/y8T9PlsuW6Y30G8ACcrBucRwCo+od9l5Pm4gj47SxPEW0BPvyYdUAjFNbDedM4=,iv:fNX12Q98V5at/TynWXGMy5JqJC9Rz/H4fQhD2gmTRa4=,tag:3AKdlfFolrGinkPdieKvpQ==,type:str]
kind: Secret
metadata:
    name: my-super-docker-hub-pull-secret
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    lastmodified: "2025-11-24T16:28:30Z"
    mac: ENC[AES256_GCM,data:AyA8/+DgwjXW+y3htk/NH+OKcBUdiWX9eFSUa7dZk1osaDZ/thv5G0HN4Sg415Rku2OrhhfLIduUHZglnVe974xloKIkjr/itpk4sOszmbyic441zisvJtZHtntPxaoqKxnCg2ykSwcBkworKO2NIqHHcgnKl0nVXXczu+vPkBQ=,iv:tzq+EmDcIj/Q8XGn9beRWF/oHsD00NBadEm6stSXdXA=,tag:Yomr8dJm9vTxqgFiZnjQOw==,type:str]
    pgp:
        - created_at: "2025-11-24T16:28:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DD39ke7DWyjoSAQdAvFIkl36xExAwQhdifOUPX8M0UzHb4ojGLgoTY8rLV3ow
            7wvFvDCq44Y/Z21SZwCL1T9ucuq/8xwp4zRW1m7gXVShkWYT3gh+3BO47RlMDNl8
            1GYBCQIQw3nuYs7M6vBIv2Z902dEefYnFnBjG/7QQlzB3dpnjAUg6dTr7oMWc+6/
            ayYCFpPEHXj2NYlOHcglAdWy4RarkHsuVONdoWqhW1cS6/rHMbxvBK5eLdWpjohh
            gs1H6xfQih4=
            =cWg2
            -----END PGP MESSAGE-----
          fp: 36CE22BE4013AB02D13D37429CA6D02C1BFE3F11
        - created_at: "2025-11-24T16:28:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2mLLTvi2YCoAQ//ba8a5/MSEyJbd561uNvHkWvOwoi1GFbkjOxU604sGUvY
            5lduxoKNUYK3dXAO9BuVfjRmDevw3eAaudJlLMjtGf2cPJV4nF/86XqUBNJEExTj
            bWMMBi7L4SUf5P+3tt/3maQGnhWAOdfDFdNT/K/h1rmf+V+3A8t/JGOedNRJkUy1
            zrCPXueQAEaEV1ImLD97OCoAaQXqPs62ei1JUYJ3Li1MdWs2TT9bQr/Simksy+ax
            90EaOru/QXMTWQRpQJG9ri39Aju/ICy9V5ZY8uf0UFF0Z2iFoQomOm9HiSj1Pe65
            ruHt2blXE6tevf5z3cktiJvLuF8u6VCNxVb7+/yXU1beGgFOPoXQf1Y7lBS4Os6d
            jVb8by8+KPlDBG1J01kGlFp4sbTFaDGNhmb3aC+cS/g9136oqRG2vThbhk4QsKVr
            14w07RuIgmaUNo45lka2KhJTnD32CmIO3HxpUWy+wlw/24DcHEzy08TWcvy3pSwo
            Om04FwyAqQ6ODPjLhvwzrl/f2bCQg+CFfpjiUCUZIqqw/2BFqhT3em71K8kEX4qg
            QeYfJ7hNJwoxfJKk6693PVLhLMnlOgPuq4MPK3BwbMiZXBFXbnyklD3TCQSZszYL
            OY8eLQZQg5O+Z+KoElxo4K+S9gtilv/QTr/uUWtqadf8sPPzSwgua2UQwpbYJUzU
            ZgEJAhA2AEus8Lg+T1cWkwA4jgZzuukv7XhFdY0t0BjkuodLEVl+CNVbiQBauq/9
            QDTSn8XPIiRuh2P+jE/dLmGWGIe6qI8v+y54SXrTHGXvaL1lzSIt8vOLR1XY33SY
            gK1AQwttFQ==
            =ETxu
            -----END PGP MESSAGE-----
          fp: 0FC1070248E009EF18EF8F3A3C17E467E8763D54
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
